// This Source Code Form is subject to the terms of the Mozilla Public
// License, v2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/

import { LayoutData } from "@foxglove/studio-base/context/CurrentLayoutContext/actions";
import { defaultPlaybackConfig } from "@foxglove/studio-base/providers/CurrentLayoutProvider/reducers";

/**
 * Overridden default layout that may have been provided when self-hosting via Docker
 * */
const staticDefaultLayout = (globalThis as { FOXGLOVE_STUDIO_DEFAULT_LAYOUT?: LayoutData })
  .FOXGLOVE_STUDIO_DEFAULT_LAYOUT;

/**
 * This is loaded when the user has no layout selected on application launch
 * to avoid presenting the user with a blank layout.
 */
export const defaultLayout: LayoutData =
  staticDefaultLayout ??
  ({
    configById: {
      "3D!rrcRobotScene": {
        cameraState: {
          distance: 10,
          perspective: true,
          phi: 50,
          target: [0, 0, 0],
          targetOffset: [0, 0, 0],
          targetOrientation: [0, 0, 0, 1],
          thetaOffset: 45,
          fovy: 45,
          near: 0.01,
          far: 5000,
        },
        scene: {},
        transforms: {},
        topics: {
          "/glim_ros/map": {
            visible: true,
            colorField: "intensity",
            colorMode: "colormap",
            colorMap: "turbo",
          },
          "/sensors/lidar/points": {
            visible: true,
            colorField: "intensity",
            colorMode: "colormap",
            colorMap: "turbo",
          },
          "/tof/points": {
            visible: true,
            colorField: "z",
            colorMode: "colormap",
            colorMap: "turbo",
          },
          "/map": { visible: true },
          "/global_costmap/costmap": { visible: true },
          "/local_costmap/costmap": { visible: true },
          "/plan": { visible: true },
          "/local_plan": { visible: true },
          "/robot_description": { visible: true },
        },
        layers: {},
        publish: {
          type: "point",
          poseTopic: "/goal_pose",
          pointTopic: "/clicked_point",
          poseEstimateTopic: "/initialpose",
          poseEstimateXDeviation: 0.5,
          poseEstimateYDeviation: 0.5,
          poseEstimateThetaDeviation: 0.26179939,
        },
        followMode: "follow-pose",
        followTf: "base_link",
        imageMode: {},
        foxglovePanelTitle: "GLIM 三维地图 / 点云 / Nav2｜/map 障碍高度 −0.03～0.75 m",
      },
      "Gauge!batteryVoltage": {
        path: "/voltage.data",
        minValue: 9,
        maxValue: 13,
        colorMode: "colormap",
        colorMap: "red-yellow-green",
        gradient: ["#e53935", "#43a047"],
        reverse: false,
        foxglovePanelTitle: "电池电压（V）",
      },
      "Plot!linearVelocity": {
        paths: [
          {
            value: "/cmd_vel.linear.x",
            enabled: true,
            timestampMethod: "receiveTime",
            label: "指令线速度",
            color: "#ff9800",
            showLine: true,
            lineSize: 2,
          },
          {
            value: "/vel_raw.linear.x",
            enabled: true,
            timestampMethod: "receiveTime",
            label: "STM32 反馈线速度",
            color: "#4caf50",
            showLine: true,
            lineSize: 2,
          },
          {
            value: "/wheel/odometry.twist.twist.linear.x",
            enabled: true,
            timestampMethod: "receiveTime",
            label: "轮式里程计线速度",
            color: "#2196f3",
            showLine: true,
            lineSize: 2,
          },
        ],
        minYValue: -0.35,
        maxYValue: 0.35,
        showXAxisLabels: true,
        showYAxisLabels: true,
        showLegend: true,
        legendDisplay: "top",
        showPlotValuesInLegend: true,
        isSynced: true,
        xAxisVal: "timestamp",
        followingViewWidth: 20,
        sidebarDimension: 0,
        foxglovePanelTitle: "线速度：指令 / STM32 / 里程计（m/s）",
      },
      "Plot!yawRate": {
        paths: [
          {
            value: "/cmd_vel.angular.z",
            enabled: true,
            timestampMethod: "receiveTime",
            label: "指令角速度",
            color: "#ff9800",
            showLine: true,
            lineSize: 2,
          },
          {
            value: "/wheel/odometry.twist.twist.angular.z",
            enabled: true,
            timestampMethod: "receiveTime",
            label: "里程计角速度",
            color: "#2196f3",
            showLine: true,
            lineSize: 2,
          },
        ],
        minYValue: -0.9,
        maxYValue: 0.9,
        showXAxisLabels: true,
        showYAxisLabels: true,
        showLegend: true,
        legendDisplay: "top",
        showPlotValuesInLegend: true,
        isSynced: true,
        xAxisVal: "timestamp",
        followingViewWidth: 20,
        sidebarDimension: 0,
        foxglovePanelTitle: "角速度：指令 / 轮式里程计（rad/s）",
      },
      "Plot!steeringAngle": {
        paths: [
          {
            value: "/vel_raw.linear.y",
            enabled: true,
            timestampMethod: "receiveTime",
            label: "STM32 转向角反馈",
            color: "#9c27b0",
            showLine: true,
            lineSize: 2,
          },
          {
            value: "30",
            enabled: true,
            timestampMethod: "receiveTime",
            label: "+30° 限位",
            color: "#ef5350",
          },
          {
            value: "-30",
            enabled: true,
            timestampMethod: "receiveTime",
            label: "-30° 限位",
            color: "#ef5350",
          },
        ],
        minYValue: -32,
        maxYValue: 32,
        showXAxisLabels: true,
        showYAxisLabels: true,
        showLegend: true,
        legendDisplay: "top",
        showPlotValuesInLegend: true,
        isSynced: true,
        xAxisVal: "timestamp",
        followingViewWidth: 20,
        sidebarDimension: 0,
        foxglovePanelTitle: "前轮转向角反馈（°）",
      },
      "Plot!imuAcceleration": {
        paths: [
          {
            value: "/imu/data_raw.linear_acceleration.x",
            enabled: true,
            timestampMethod: "receiveTime",
            label: "加速度 X",
            color: "#ef5350",
          },
          {
            value: "/imu/data_raw.linear_acceleration.y",
            enabled: true,
            timestampMethod: "receiveTime",
            label: "加速度 Y",
            color: "#66bb6a",
          },
          {
            value: "/imu/data_raw.linear_acceleration.z",
            enabled: true,
            timestampMethod: "receiveTime",
            label: "加速度 Z",
            color: "#42a5f5",
          },
        ],
        minYValue: -15,
        maxYValue: 15,
        showXAxisLabels: true,
        showYAxisLabels: true,
        showLegend: true,
        legendDisplay: "top",
        showPlotValuesInLegend: true,
        isSynced: true,
        xAxisVal: "timestamp",
        followingViewWidth: 20,
        sidebarDimension: 0,
        foxglovePanelTitle: "STM32 IMU 线加速度（m/s²）",
      },
      "Plot!imuAngularVelocity": {
        paths: [
          {
            value: "/imu/data_raw.angular_velocity.x",
            enabled: true,
            timestampMethod: "receiveTime",
            label: "角速度 X",
            color: "#ef5350",
          },
          {
            value: "/imu/data_raw.angular_velocity.y",
            enabled: true,
            timestampMethod: "receiveTime",
            label: "角速度 Y",
            color: "#66bb6a",
          },
          {
            value: "/imu/data_raw.angular_velocity.z",
            enabled: true,
            timestampMethod: "receiveTime",
            label: "角速度 Z",
            color: "#42a5f5",
          },
        ],
        minYValue: -2,
        maxYValue: 2,
        showXAxisLabels: true,
        showYAxisLabels: true,
        showLegend: true,
        legendDisplay: "top",
        showPlotValuesInLegend: true,
        isSynced: true,
        xAxisVal: "timestamp",
        followingViewWidth: 20,
        sidebarDimension: 0,
        foxglovePanelTitle: "STM32 IMU 角速度（rad/s）",
      },
      "Plot!imuMagneticField": {
        paths: [
          {
            value: "/imu/mag.magnetic_field.x",
            enabled: true,
            timestampMethod: "receiveTime",
            label: "磁场 X",
            color: "#ef5350",
          },
          {
            value: "/imu/mag.magnetic_field.y",
            enabled: true,
            timestampMethod: "receiveTime",
            label: "磁场 Y",
            color: "#66bb6a",
          },
          {
            value: "/imu/mag.magnetic_field.z",
            enabled: true,
            timestampMethod: "receiveTime",
            label: "磁场 Z",
            color: "#42a5f5",
          },
        ],
        showXAxisLabels: true,
        showYAxisLabels: true,
        showLegend: true,
        legendDisplay: "top",
        showPlotValuesInLegend: true,
        isSynced: true,
        xAxisVal: "timestamp",
        followingViewWidth: 20,
        sidebarDimension: 0,
        foxglovePanelTitle: "STM32 三轴磁场",
      },
      "RawMessages!editionStatus": {
        topicPath: "/edition",
        expansion: "all",
        fontSize: 14,
        foxglovePanelTitle: "STM32 串口 / 固件状态（/edition）",
      },
      "RawMessages!wheelOverview": {
        topicPath: "/wheel/odometry",
        expansion: "all",
        fontSize: 11,
        foxglovePanelTitle: "轮式里程计实时值",
      },
      "RawMessages!imuRaw": {
        topicPath: "/imu/data_raw",
        expansion: "all",
        fontSize: 11,
        foxglovePanelTitle: "STM32 IMU 原始消息",
      },
      "RawMessages!cmdVel": {
        topicPath: "/cmd_vel",
        expansion: "all",
        fontSize: 12,
        foxglovePanelTitle: "底盘最终速度指令（/cmd_vel）",
      },
      "RawMessages!velRaw": {
        topicPath: "/vel_raw",
        expansion: "all",
        fontSize: 12,
        foxglovePanelTitle: "STM32 速度与转角反馈（/vel_raw）",
      },
      "RawMessages!wheelOdometry": {
        topicPath: "/wheel/odometry",
        expansion: "all",
        fontSize: 11,
        foxglovePanelTitle: "轮式里程计（/wheel/odometry）",
      },
      "RawMessages!jointStates": {
        topicPath: "/joint_states",
        expansion: "all",
        fontSize: 11,
        foxglovePanelTitle: "车轮与转向关节（/joint_states）",
      },
    },
    globalVariables: {},
    userNodes: {},
    playbackConfig: { ...defaultPlaybackConfig },
    layout: {
      direction: "row",
      splitPercentage: 21,
      first: {
        direction: "column",
        splitPercentage: 16,
        first: "Gauge!batteryVoltage",
        second: {
          direction: "column",
          splitPercentage: 40,
          first: "Plot!linearVelocity",
          second: {
            direction: "column",
            splitPercentage: 50,
            first: "Plot!yawRate",
            second: "Plot!steeringAngle",
          },
        },
      },
      second: {
        direction: "row",
        splitPercentage: 76,
        first: "3D!rrcRobotScene",
        second: {
          direction: "column",
          splitPercentage: 44,
          first: "Plot!imuAcceleration",
          second: {
            direction: "column",
            splitPercentage: 78,
            first: "Plot!imuAngularVelocity",
            second: "RawMessages!editionStatus",
          },
        },
      },
    },
  } as const);
